# SQLite3 for development and test, PostgreSQL via DATABASE_URL in production.

default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: db/development/app_db.sqlite3
  queue:
    <<: *default
    database: db/development/queue_db.sqlite3
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: db/test/app_db.sqlite3
  queue:
    <<: *default
    database: db/test/queue_db.sqlite3
    migrations_paths: db/queue_migrate

production:
  primary:
    <<: *default
    database: storage/db/production.sqlite3
  queue:
    <<: *default
    database: storage/db/production_queue.sqlite3
    migrations_paths: db/queue_migrate
